services:
  userservice_app:
    build:
      context: userservice
      args:
        firebase_service_account_file: firebase_service_account_file.json
    container_name: userservice_app
    depends_on:
      - userservice_db
      - eurekaserver_app
    ports:
      - 8081:8080
    networks:
      userservice_internal:
      internal:
        aliases:
          - userservice

  userservice_db:
    image: postgres
    container_name: userservice_db
    restart: unless-stopped
    volumes:
      - userservice_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      userservice_internal:
        aliases:
          - userservicedb

  apigateway_app:
    build:
      context: apigateway
    container_name: apigateway_app
    depends_on:
      - eurekaserver_app
    ports:
      - 8080:8080
    networks:
      - internal

  eurekaserver_app:
    build:
      context: eurekaServer
    container_name: eurekaserver_app
    ports:
      - 8761:8761
    networks:
      internal:
        aliases:
          - eurekaserver

#  rabbitmq:
#    build:
#      context: rabbitMQ
#    container_name: rabbitMQ
#    restart: unless-stopped
#    ports:
#      - 5672:5672
#      - 15672:15672 # management
#    networks:
#      - internal


volumes:
  userservice_db_data: {}

networks:
  internal : {}
  userservice_internal: {}
