apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o config/
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: apigateway-app
  name: apigateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o config/
        kompose.image-pull-policy: Never
        kompose.service.type: loadbalancer
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kubernetes-internal: "true"
        io.kompose.service: apigateway-app
    spec:
      containers:
        - image: appunto-apigateway-app
          imagePullPolicy: Never
          name: apigateway-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
