apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o config/
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: apigateway-app-tcp
  name: apigateway-app-tcp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: apigateway-app
  type: LoadBalancer
