apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o config/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: fileservice-db
  name: fileservice-db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: fileservice-db
