apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file compose.yaml --out config
    kompose.image-pull-policy: Never
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: forumservice-app
  name: forumservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forumservice-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file compose.yaml --out config
        kompose.image-pull-policy: Never
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kubernetes-forumservice-internal: "true"
        io.kompose.network/kubernetes-internal: "true"
        io.kompose.service: forumservice-app
    spec:
      containers:
        - image: appunto-forumservice-app
          imagePullPolicy: Never
          name: forumservice-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
