apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file compose.yaml --out config
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: forumservice-db
  name: forumservice-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forumservice-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file compose.yaml --out config
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kubernetes-forumservice-internal: "true"
        io.kompose.service: forumservice-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: forumservice
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: postgres
          name: forumservice-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: forumservice-db-data
      restartPolicy: Always
      volumes:
        - name: forumservice-db-data
          persistentVolumeClaim:
            claimName: forumservice-db-data
