apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file compose.yaml --out config
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: messageservice-app
  name: messageservice-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: messageservice-app
