apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Simone Multari\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out .\tmp\
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: messageservice-db
  name: messageservice-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: messageservice-db
status:
  loadBalancer: {}
