apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file compose.yaml --out config
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: userservice-db
  name: userservice-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: userservice-db
