services:
  app:
    build:
      context: .
    networks:
      - internal

  db:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  data: {}

networks:
  internal:
    driver: bridge