@docker-https-port = 57596
@default-uid = GtO6PJ07MlTP5J2ALrEMFV7w4Pz1

### test
GET http://localhost:8080/user/info?uid={{default-uid}}

### getUserById
GET http://localhost:{{docker-https-port}}/user/info?uid={{default-uid}}

### enroll
GET http://localhost:{{docker-https-port}}/user/enroll?uid={{default-uid}}&courseId=123

### leave
GET http://localhost:{{docker-https-port}}/user/leave?uid={{default-uid}}&courseId=123