services:
  app:
    build:
      context: .
      args:
        firebase_service_account_file: firebase_service_account_file.json
    container_name: app
    networks:
      - internal

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - internal

volumes:
  data: {}

networks:
  internal:
    driver: bridge