services:
  app:
    build:
      context: .
      args:
        firebase_service_account_file: firebase_service_account_file.json
    container_name: app
    depends_on:
      - db
      - rabbitmq
    networks:
      - internal
      - rabbitmq

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - internal

  rabbitmq:
    build:
      context: ../rabbitMQ
    container_name: rabbitMQ
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672 # management
    networks:
      - rabbitmq


volumes:
  data: {}

networks:
  internal: {}
  rabbitmq: {}
